url: https://rsim-tu-berlin.github.io
baseurl: /rsim.tu-berlin.de
collections_dir: content
collections:
  team:
    output: true
    sort_by: order
    permalink: /:collection/members/:name
  teaching_current_semester:
    output: true
    permalink: /teaching/:path
  teaching_past_semesters:
    output: true
    permalink: /teaching/:path
  news:
    sort_by: date
  projects:
    sort_by: date
  software:
    sort_by: date
  theses:
    sort_by: date