site: RSiM Site
group_name: RSiM
rsim_mainpage: https://www.rsim.tu-berlin.de

tu_berlin_mainpage: https://tu.berlin
tu_berlin_eecs_mainpage: https://www.eecs.tu-berlin.de/menue/faculty_iv_electrical_engineering_and_computer_science/
bifold_mainpage: https://www.bifold.berlin
erc_mainpage: https://erc.europa.eu
bmbf_mainpage: https://www.bmbf.de
bmwi_mainpage: https://www.bmwi.de
dfg_mainpage: https://www.dfg.de
google_mainpage: https://research.google.com
esa_mainpage: https://www.esa.int

publications:
  journals: "International Journals"
  conferences: "International Conferences"
  books: "Book Chapters"
